"""Views for the tasks app."""

from .home_view import home
from .log_in_view import LogInView
from .log_out_view import log_out
from .password_view import PasswordView
from .profile_update_view import ProfileUpdateView
from .customisation_view import CustomisationView
from .update_profile_picture_view import update_profile_picture
from .sign_up_view import SignUpView
from .view_mixins import LoginProhibitedMixin
from .profile_deactivate_view import deactivate_user
from .conversation_view import ConversationView
from .find_friends_view import PeerSelectView
from .create_conversation_view import CreateConversationView
from .new_question_page_view import new_question_page
from .reply_page_view import ReplyPageView
from .resources_view import ResourcesView
from .question_page_view import QuestionPageView
from .send_friend_request_view import SendFriendRequestView
from .accept_friend_request_view import AcceptFriendRequestView
from .friends_list_view import FriendsListView
from .other_user_settings_view import OtherUserSettingsView
from .block_user_view import BlockUserView
from .unblock_user_view import UnblockUserView
from .profile_view import ProfileView
from .inbox_view import InboxView
from .delete_notification_view import delete_notification
from .clear_notifications_view import clear_notifications
from .post_view import PostView
from .delete_post_view import DeletePostView
from .feed_view import FeedView
from .like_post_view import LikePostView
from .conversation_details_view import ConversationDetailsView
from .remove_friend_view import remove_friend
from .moderation_view import ModerationView
from .accept_report_view import AcceptReportView
from .decline_report_view import DeclineReportView
from .leave_conversation_view import LeaveConversationView
from .information_view import InformationView
from .delete_conversation_view import DeleteConversationView
from .submit_feedback_view import SubmitFeedbackView
from .feedback_view import FeedbackView
from .delete_feedback_view import delete_feedback
from .demographic_information_view import DemographicInformationView
from .delete_question_view import delete_question
from .delete_reply_view import delete_reply
from .delete_comment_view import DeleteCommentView
from .accessibility_view import AccessibilityView
