# Generated by Django 4.2.10 on 2024-03-05 17:09

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must consist of @ followed by at least three alphanumericals', regex='^@\\w{3,}$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=50)),
                ('location', models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia, Plurinational State of'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet Island'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'), ('BN', 'Brunei Darussalam'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cabo Verde'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling) Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CD', 'Congo, The Democratic Republic of the'), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('CI', "Côte d'Ivoire"), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('TF', 'French Southern Territories'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard Island and McDonald Islands'), ('VA', 'Holy See (Vatican City State)'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran, Islamic Republic of'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KP', "Korea, Democratic People's Republic of"), ('KR', 'Korea, Republic of'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', "Lao People's Democratic Republic"), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia, Federated States of'), ('MD', 'Moldova, Republic of'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'), ('MK', 'North Macedonia'), ('MP', 'Northern Mariana Islands'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestine, State of'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('RE', 'Réunion'), ('BL', 'Saint Barthélemy'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French part)'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SX', 'Sint Maarten (Dutch part)'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('GS', 'South Georgia and the South Sandwich Islands'), ('SS', 'South Sudan'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syrian Arab Republic'), ('TW', 'Taiwan, Province of China'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania, United Republic of'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('TR', 'Türkiye'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('US', 'United States'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela, Bolivarian Republic of'), ('VN', 'Viet Nam'), ('VG', 'Virgin Islands, British'), ('VI', 'Virgin Islands, U.S.'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('AX', 'Åland Islands')], max_length=50)),
                ('hospital', models.CharField(blank=True, choices=[('Airedale NHS Foundation Trust', 'Airedale NHS Foundation Trust'), ('Alder Hey Children’s NHS Foundation Trust', 'Alder Hey Children’s NHS Foundation Trust'), ('Ashford and St Peter’s Hospitals NHS Foundation Trust', 'Ashford and St Peter’s Hospitals NHS Foundation Trust'), ('Avon and Wiltshire Mental Health Partnership NHS Trust', 'Avon and Wiltshire Mental Health Partnership NHS Trust'), ('Barking, Havering and Redbridge University Hospitals NHS Trust', 'Barking, Havering and Redbridge University Hospitals NHS Trust'), ('Barnet, Enfield and Haringey Mental Health NHS Trust', 'Barnet, Enfield and Haringey Mental Health NHS Trust'), ('Barnsley Hospital NHS Foundation Trust', 'Barnsley Hospital NHS Foundation Trust'), ('Barts Health NHS Trust', 'Barts Health NHS Trust'), ('Bedfordshire Hospitals NHS Foundation Trust', 'Bedfordshire Hospitals NHS Foundation Trust'), ('Berkshire Healthcare NHS Foundation Trust', 'Berkshire Healthcare NHS Foundation Trust'), ('Birmingham and Solihull Mental Health NHS Foundation Trust', 'Birmingham and Solihull Mental Health NHS Foundation Trust'), ('Birmingham Community Healthcare NHS Foundation Trust', 'Birmingham Community Healthcare NHS Foundation Trust'), ('Birmingham Women’s and Children’s NHS Foundation Trust', 'Birmingham Women’s and Children’s NHS Foundation Trust'), ('Black Country Healthcare NHS Foundation Trust', 'Black Country Healthcare NHS Foundation Trust'), ('Blackpool Teaching Hospitals NHS Foundation Trust', 'Blackpool Teaching Hospitals NHS Foundation Trust'), ('Bolton NHS Foundation Trust', 'Bolton NHS Foundation Trust'), ('Bradford District Care NHS Foundation Trust', 'Bradford District Care NHS Foundation Trust'), ('Bradford Teaching Hospitals NHS Foundation Trust', 'Bradford Teaching Hospitals NHS Foundation Trust'), ('Bridgewater Community Healthcare NHS Foundation Trust', 'Bridgewater Community Healthcare NHS Foundation Trust'), ('Buckinghamshire Healthcare NHS Trust', 'Buckinghamshire Healthcare NHS Trust'), ('Calderdale and Huddersfield NHS Foundation Trust', 'Calderdale and Huddersfield NHS Foundation Trust'), ('Cambridge University Hospitals NHS Foundation Trust', 'Cambridge University Hospitals NHS Foundation Trust'), ('Cambridgeshire and Peterborough NHS Foundation Trust', 'Cambridgeshire and Peterborough NHS Foundation Trust'), ('Cambridgeshire Community Services NHS Trust', 'Cambridgeshire Community Services NHS Trust'), ('Camden and Islington NHS Foundation Trust', 'Camden and Islington NHS Foundation Trust'), ('Central and North West London NHS Foundation Trust', 'Central and North West London NHS Foundation Trust'), ('Central London Community Healthcare NHS Trust', 'Central London Community Healthcare NHS Trust'), ('Chelsea and Westminster Hospital NHS Foundation Trust', 'Chelsea and Westminster Hospital NHS Foundation Trust'), ('Cheshire and Wirral Partnership NHS Foundation Trust', 'Cheshire and Wirral Partnership NHS Foundation Trust'), ('Chesterfield Royal Hospital NHS Foundation Trust', 'Chesterfield Royal Hospital NHS Foundation Trust'), ('Cornwall Partnership NHS Foundation Trust', 'Cornwall Partnership NHS Foundation Trust'), ('Countess of Chester Hospital NHS Foundation Trust', 'Countess of Chester Hospital NHS Foundation Trust'), ('County Durham and Darlington NHS Foundation Trust', 'County Durham and Darlington NHS Foundation Trust'), ('Coventry and Warwickshire Partnership NHS Trust', 'Coventry and Warwickshire Partnership NHS Trust'), ('Croydon Health Services NHS Trust', 'Croydon Health Services NHS Trust'), ('Cumbria, Northumberland, Tyne and Wear NHS Foundation Trust', 'Cumbria, Northumberland, Tyne and Wear NHS Foundation Trust'), ('Dartford and Gravesham NHS Trust', 'Dartford and Gravesham NHS Trust'), ('Derbyshire Community Health Services NHS Foundation Trust', 'Derbyshire Community Health Services NHS Foundation Trust'), ('Derbyshire Healthcare NHS Foundation Trust', 'Derbyshire Healthcare NHS Foundation Trust'), ('Devon Partnership NHS Trust', 'Devon Partnership NHS Trust'), ('Doncaster and Bassetlaw Teaching Hospitals NHS Foundation Trust', 'Doncaster and Bassetlaw Teaching Hospitals NHS Foundation Trust'), ('Dorset County Hospital NHS Foundation Trust', 'Dorset County Hospital NHS Foundation Trust'), ('Dorset Healthcare University NHS Foundation Trust', 'Dorset Healthcare University NHS Foundation Trust'), ('Dudley Integrated Health and Care NHS Trust', 'Dudley Integrated Health and Care NHS Trust'), ('East Cheshire NHS Trust', 'East Cheshire NHS Trust'), ('East and North Hertfordshire NHS Trust', 'East and North Hertfordshire NHS Trust'), ('East Kent Hospitals University NHS Foundation Trust', 'East Kent Hospitals University NHS Foundation Trust'), ('East Lancashire Hospitals NHS Trust', 'East Lancashire Hospitals NHS Trust'), ('East London NHS Foundation Trust', 'East London NHS Foundation Trust'), ('East Midlands Ambulance Service NHS Trust', 'East Midlands Ambulance Service NHS Trust'), ('East of England Ambulance Service NHS Trust', 'East of England Ambulance Service NHS Trust'), ('East Suffolk and North Essex NHS Foundation Trust', 'East Suffolk and North Essex NHS Foundation Trust'), ('East Sussex Healthcare NHS Trust', 'East Sussex Healthcare NHS Trust'), ('Epsom and St Helier University Hospitals NHS Trust', 'Epsom and St Helier University Hospitals NHS Trust'), ('Essex Partnership University NHS Foundation Trust', 'Essex Partnership University NHS Foundation Trust'), ('Frimley Health NHS Foundation Trust', 'Frimley Health NHS Foundation Trust'), ('Gateshead Health NHS Foundation Trust', 'Gateshead Health NHS Foundation Trust'), ('George Eliot Hospital NHS Trust', 'George Eliot Hospital NHS Trust'), ('Gloucestershire Health and Care NHS Foundation Trust', 'Gloucestershire Health and Care NHS Foundation Trust'), ('Gloucestershire Hospitals NHS Foundation Trust', 'Gloucestershire Hospitals NHS Foundation Trust'), ('Great Ormond Street Hospital For Children NHS Foundation Trust', 'Great Ormond Street Hospital For Children NHS Foundation Trust'), ('Great Western Hospitals NHS Foundation Trust', 'Great Western Hospitals NHS Foundation Trust'), ('Greater Manchester Mental Health NHS Foundation Trust', 'Greater Manchester Mental Health NHS Foundation Trust'), ('Guy’s and St Thomas’ NHS Foundation Trust', 'Guy’s and St Thomas’ NHS Foundation Trust'), ('Hampshire Hospitals NHS Foundation Trust', 'Hampshire Hospitals NHS Foundation Trust'), ('Harrogate and District NHS Foundation Trust', 'Harrogate and District NHS Foundation Trust'), ('Herefordshire and Worcestershire Health and Care NHS Trust', 'Herefordshire and Worcestershire Health and Care NHS Trust'), ('Hertfordshire Community NHS Trust', 'Hertfordshire Community NHS Trust'), ('Hertfordshire Partnership University NHS Foundation Trust', 'Hertfordshire Partnership University NHS Foundation Trust'), ('Homerton Healthcare NHS Foundation Trust', 'Homerton Healthcare NHS Foundation Trust'), ('Hounslow and Richmond Community Healthcare NHS Trust', 'Hounslow and Richmond Community Healthcare NHS Trust'), ('Hull University Teaching Hospitals NHS Trust', 'Hull University Teaching Hospitals NHS Trust'), ('Humber Teaching NHS Foundation Trust', 'Humber Teaching NHS Foundation Trust'), ('Imperial College Healthcare NHS Trust', 'Imperial College Healthcare NHS Trust'), ('Isle of Wight NHS Trust', 'Isle of Wight NHS Trust'), ('James Paget University Hospitals NHS Foundation Trust', 'James Paget University Hospitals NHS Foundation Trust'), ('Kent and Medway NHS and Social Care Partnership Trust', 'Kent and Medway NHS and Social Care Partnership Trust'), ('Kent Community Health NHS Foundation Trust', 'Kent Community Health NHS Foundation Trust'), ('Kettering General Hospital NHS Foundation Trust', 'Kettering General Hospital NHS Foundation Trust'), ('King’s College Hospital NHS Foundation Trust', 'King’s College Hospital NHS Foundation Trust'), ('Kingston Hospital NHS Foundation Trust', 'Kingston Hospital NHS Foundation Trust'), ('Lancashire and South Cumbria NHS Foundation Trust', 'Lancashire and South Cumbria NHS Foundation Trust'), ('Lancashire Teaching Hospitals NHS Foundation Trust', 'Lancashire Teaching Hospitals NHS Foundation Trust'), ('Leeds Community Healthcare NHS Trust', 'Leeds Community Healthcare NHS Trust'), ('Leeds Teaching Hospitals NHS Trust', 'Leeds Teaching Hospitals NHS Trust'), ('Leeds and York Partnership NHS Foundation Trust', 'Leeds and York Partnership NHS Foundation Trust'), ('Leicestershire Partnership NHS Trust', 'Leicestershire Partnership NHS Trust'), ('Lewisham and Greenwich NHS Trust', 'Lewisham and Greenwich NHS Trust'), ('Lincolnshire Community Health Services NHS Trust', 'Lincolnshire Community Health Services NHS Trust'), ('Lincolnshire Partnership NHS Foundation Trust', 'Lincolnshire Partnership NHS Foundation Trust'), ('Liverpool Heart and Chest Hospital NHS Foundation Trust', 'Liverpool Heart and Chest Hospital NHS Foundation Trust'), ('Liverpool University Hospitals NHS Foundation Trust', 'Liverpool University Hospitals NHS Foundation Trust'), ('Liverpool Women’s NHS Foundation Trust', 'Liverpool Women’s NHS Foundation Trust'), ('London Ambulance Service NHS Trust', 'London Ambulance Service NHS Trust'), ('London North West University Healthcare NHS Trust', 'London North West University Healthcare NHS Trust'), ('Maidstone and Tunbridge Wells NHS Trust', 'Maidstone and Tunbridge Wells NHS Trust'), ('Manchester University NHS Foundation Trust', 'Manchester University NHS Foundation Trust'), ('Medway NHS Foundation Trust', 'Medway NHS Foundation Trust'), ('Mersey Care NHS Foundation Trust', 'Mersey Care NHS Foundation Trust'), ('Mersey and West Lancashire Teaching Hospitals NHS Trust', 'Mersey and West Lancashire Teaching Hospitals NHS Trust'), ('Mid and South Essex NHS Foundation Trust', 'Mid and South Essex NHS Foundation Trust'), ('Mid Cheshire Hospitals NHS Foundation Trust', 'Mid Cheshire Hospitals NHS Foundation Trust'), ('Mid Yorkshire Hospitals NHS Trust', 'Mid Yorkshire Hospitals NHS Trust'), ('Midlands Partnership University NHS Foundation Trust', 'Midlands Partnership University NHS Foundation Trust'), ('Milton Keynes University Hospital NHS Foundation Trust', 'Milton Keynes University Hospital NHS Foundation Trust'), ('Moorfields Eye Hospital NHS Foundation Trust', 'Moorfields Eye Hospital NHS Foundation Trust'), ('Norfolk Community Health and Care NHS Trust', 'Norfolk Community Health and Care NHS Trust'), ('Norfolk and Norwich University Hospitals NHS Foundation Trust', 'Norfolk and Norwich University Hospitals NHS Foundation Trust'), ('Norfolk and Suffolk NHS Foundation Trust', 'Norfolk and Suffolk NHS Foundation Trust'), ('North Bristol NHS Trust', 'North Bristol NHS Trust'), ('North Cumbria Integrated Care NHS Foundation Trust', 'North Cumbria Integrated Care NHS Foundation Trust'), ('North East Ambulance Service NHS Foundation Trust', 'North East Ambulance Service NHS Foundation Trust'), ('North East London NHS Foundation Trust', 'North East London NHS Foundation Trust'), ('Northern Care Alliance NHS Foundation Trust', 'Northern Care Alliance NHS Foundation Trust'), ('North Middlesex University Hospital NHS Trust', 'North Middlesex University Hospital NHS Trust'), ('North Staffordshire Combined Healthcare NHS Trust', 'North Staffordshire Combined Healthcare NHS Trust'), ('North Tees and Hartlepool NHS Foundation Trust', 'North Tees and Hartlepool NHS Foundation Trust'), ('North West Ambulance Service NHS Trust', 'North West Ambulance Service NHS Trust'), ('North West Anglia NHS Foundation Trust', 'North West Anglia NHS Foundation Trust'), ('North West Boroughs Healthcare NHS Foundation Trust', 'North West Boroughs Healthcare NHS Foundation Trust'), ('Northampton General Hospital NHS Trust', 'Northampton General Hospital NHS Trust'), ('Northamptonshire Healthcare NHS Foundation Trust', 'Northamptonshire Healthcare NHS Foundation Trust'), ('Northern Lincolnshire and Goole NHS Foundation Trust', 'Northern Lincolnshire and Goole NHS Foundation Trust'), ('Northumbria Healthcare NHS Foundation Trust', 'Northumbria Healthcare NHS Foundation Trust'), ('Nottingham University Hospitals NHS Trust', 'Nottingham University Hospitals NHS Trust'), ('Nottinghamshire Healthcare NHS Foundation Trust', 'Nottinghamshire Healthcare NHS Foundation Trust'), ('Oxford Health NHS Foundation Trust', 'Oxford Health NHS Foundation Trust'), ('Oxford University Hospitals NHS Foundation Trust', 'Oxford University Hospitals NHS Foundation Trust'), ('Oxleas NHS Foundation Trust', 'Oxleas NHS Foundation Trust'), ('Pennine Care NHS Foundation Trust', 'Pennine Care NHS Foundation Trust'), ('Portsmouth Hospitals University NHS Trust', 'Portsmouth Hospitals University NHS Trust'), ('Queen Victoria Hospital NHS Foundation Trust', 'Queen Victoria Hospital NHS Foundation Trust'), ('Rotherham Doncaster and South Humber NHS Foundation Trust', 'Rotherham Doncaster and South Humber NHS Foundation Trust'), ('Royal Berkshire NHS Foundation Trust', 'Royal Berkshire NHS Foundation Trust'), ('Royal Brompton and Harefield NHS Foundation Trust', 'Royal Brompton and Harefield NHS Foundation Trust'), ('Royal Cornwall Hospitals NHS Trust', 'Royal Cornwall Hospitals NHS Trust'), ('Royal Devon University Healthcare NHS Foundation Trust', 'Royal Devon University Healthcare NHS Foundation Trust'), ('Royal Free London NHS Foundation Trust', 'Royal Free London NHS Foundation Trust'), ('Royal National Orthopaedic Hospital NHS Trust', 'Royal National Orthopaedic Hospital NHS Trust'), ('Royal Papworth Hospital NHS Foundation Trust', 'Royal Papworth Hospital NHS Foundation Trust'), ('Royal Surrey NHS Foundation Trust', 'Royal Surrey NHS Foundation Trust'), ('Royal United Hospitals Bath NHS Foundation Trust', 'Royal United Hospitals Bath NHS Foundation Trust'), ('Salisbury NHS Foundation Trust', 'Salisbury NHS Foundation Trust'), ('Sandwell and West Birmingham Hospitals NHS Trust', 'Sandwell and West Birmingham Hospitals NHS Trust'), ('Sheffield Children’s NHS Foundation Trust', 'Sheffield Children’s NHS Foundation Trust'), ('Sheffield Health and Social Care NHS Foundation Trust', 'Sheffield Health and Social Care NHS Foundation Trust'), ('Sheffield Teaching Hospitals NHS Foundation Trust', 'Sheffield Teaching Hospitals NHS Foundation Trust'), ('Sherwood Forest Hospitals NHS Foundation Trust', 'Sherwood Forest Hospitals NHS Foundation Trust'), ('Shrewsbury and Telford Hospital NHS Trust', 'Shrewsbury and Telford Hospital NHS Trust'), ('Shropshire Community Health NHS Trust', 'Shropshire Community Health NHS Trust'), ('Solent NHS Trust', 'Solent NHS Trust'), ('Somerset NHS Foundation Trust', 'Somerset NHS Foundation Trust'), ('South Central Ambulance Service NHS Foundation Trust', 'South Central Ambulance Service NHS Foundation Trust'), ('South East Coast Ambulance Service NHS Foundation Trust', 'South East Coast Ambulance Service NHS Foundation Trust'), ('South London and Maudsley NHS Foundation Trust', 'South London and Maudsley NHS Foundation Trust'), ('South Tees Hospitals NHS Foundation Trust', 'South Tees Hospitals NHS Foundation Trust'), ('South Tyneside and Sunderland NHS Foundation Trust', 'South Tyneside and Sunderland NHS Foundation Trust'), ('South Warwickshire NHS Foundation Trust', 'South Warwickshire NHS Foundation Trust'), ('South West London and St George’s Mental Health NHS Trust', 'South West London and St George’s Mental Health NHS Trust'), ('South West Yorkshire Partnership NHS Foundation Trust', 'South West Yorkshire Partnership NHS Foundation Trust'), ('South Western Ambulance Service NHS Foundation Trust', 'South Western Ambulance Service NHS Foundation Trust'), ('Southern Health NHS Foundation Trust', 'Southern Health NHS Foundation Trust'), ('Southport and Ormskirk Hospital NHS Trust', 'Southport and Ormskirk Hospital NHS Trust'), ('St George’s University Hospitals NHS Foundation Trust', 'St George’s University Hospitals NHS Foundation Trust'), ('St Helens and Knowsley Teaching Hospitals NHS Trust', 'St Helens and Knowsley Teaching Hospitals NHS Trust'), ('Stockport NHS Foundation Trust', 'Stockport NHS Foundation Trust'), ('Surrey and Borders Partnership NHS Foundation Trust', 'Surrey and Borders Partnership NHS Foundation Trust'), ('Surrey and Sussex Healthcare NHS Trust', 'Surrey and Sussex Healthcare NHS Trust'), ('Sussex Community NHS Foundation Trust', 'Sussex Community NHS Foundation Trust'), ('Sussex Partnership NHS Foundation Trust', 'Sussex Partnership NHS Foundation Trust'), ('Tameside and Glossop Integrated Care NHS Foundation Trust', 'Tameside and Glossop Integrated Care NHS Foundation Trust'), ('Tavistock and Portman NHS Foundation Trust', 'Tavistock and Portman NHS Foundation Trust'), ('Tees, Esk and Wear Valleys NHS Foundation Trust', 'Tees, Esk and Wear Valleys NHS Foundation Trust'), ('Torbay and South Devon NHS Foundation Trust', 'Torbay and South Devon NHS Foundation Trust'), ('The Christie NHS Foundation Trust', 'The Christie NHS Foundation Trust'), ('The Clatterbridge Cancer Centre NHS Foundation Trust', 'The Clatterbridge Cancer Centre NHS Foundation Trust'), ('The Dudley Group NHS Foundation Trust', 'The Dudley Group NHS Foundation Trust'), ('The Hillingdon Hospitals NHS Foundation Trust', 'The Hillingdon Hospitals NHS Foundation Trust'), ('The Newcastle Upon Tyne Hospitals NHS Foundation Trust', 'The Newcastle Upon Tyne Hospitals NHS Foundation Trust'), ('The Princess Alexandra Hospital NHS Trust', 'The Princess Alexandra Hospital NHS Trust'), ('The Queen Elizabeth Hospital, King’s Lynn, NHS Foundation Trust', 'The Queen Elizabeth Hospital, King’s Lynn, NHS Foundation Trust'), ('The Robert Jones and Agnes Hunt Orthopaedic Hospital NHS Foundation Trust', 'The Robert Jones and Agnes Hunt Orthopaedic Hospital NHS Foundation Trust'), ('The Rotherham NHS Foundation Trust', 'The Rotherham NHS Foundation Trust'), ('The Royal Orthopaedic Hospital NHS Foundation Trust', 'The Royal Orthopaedic Hospital NHS Foundation Trust'), ('The Royal Marsden NHS Foundation Trust', 'The Royal Marsden NHS Foundation Trust'), ('The Royal Wolverhampton NHS Trust', 'The Royal Wolverhampton NHS Trust'), ('The Walton Centre NHS Foundation Trust', 'The Walton Centre NHS Foundation Trust'), ('University College London Hospitals NHS Foundation Trust', 'University College London Hospitals NHS Foundation Trust'), ('United Lincolnshire Hospitals NHS Trust', 'United Lincolnshire Hospitals NHS Trust'), ('University Hospital Southampton NHS Foundation Trust', 'University Hospital Southampton NHS Foundation Trust'), ('University Hospitals Birmingham NHS Foundation Trust', 'University Hospitals Birmingham NHS Foundation Trust'), ('University Hospitals Bristol and Weston NHS Foundation Trust', 'University Hospitals Bristol and Weston NHS Foundation Trust'), ('University Hospitals Coventry and Warwickshire NHS Trust', 'University Hospitals Coventry and Warwickshire NHS Trust'), ('University Hospitals of Derby and Burton NHS Foundation Trust', 'University Hospitals of Derby and Burton NHS Foundation Trust'), ('University Hospitals Dorset NHS Foundation Trust', 'University Hospitals Dorset NHS Foundation Trust'), ('University Hospitals of Leicester NHS Trust', 'University Hospitals of Leicester NHS Trust'), ('University Hospitals of Morecambe Bay NHS Foundation Trust', 'University Hospitals of Morecambe Bay NHS Foundation Trust'), ('University Hospitals of North Midlands NHS Trust', 'University Hospitals of North Midlands NHS Trust'), ('University Hospitals Plymouth NHS Trust', 'University Hospitals Plymouth NHS Trust'), ('University Hospitals Sussex NHS Foundation Trust', 'University Hospitals Sussex NHS Foundation Trust'), ('Walsall Healthcare NHS Trust', 'Walsall Healthcare NHS Trust'), ('Warrington and Halton Teaching Hospitals NHS Foundation Trust', 'Warrington and Halton Teaching Hospitals NHS Foundation Trust'), ('West Hertfordshire Hospitals NHS Trust', 'West Hertfordshire Hospitals NHS Trust'), ('West London NHS Trust', 'West London NHS Trust'), ('West Midlands Ambulance Service NHS Foundation Trust', 'West Midlands Ambulance Service NHS Foundation Trust'), ('West Suffolk NHS Foundation Trust', 'West Suffolk NHS Foundation Trust'), ('Whittington Health NHS Trust', 'Whittington Health NHS Trust'), ('Wirral Community NHS Foundation Trust', 'Wirral Community NHS Foundation Trust'), ('Wirral University Teaching Hospital NHS Foundation Trust', 'Wirral University Teaching Hospital NHS Foundation Trust'), ('Worcestershire Acute Hospitals NHS Trust', 'Worcestershire Acute Hospitals NHS Trust'), ('Wrightington, Wigan and Leigh NHS Foundation Trust', 'Wrightington, Wigan and Leigh NHS Foundation Trust'), ('Wye Valley NHS Trust', 'Wye Valley NHS Trust'), ('York and Scarborough Teaching Hospitals NHS Foundation Trust', 'York and Scarborough Teaching Hospitals NHS Foundation Trust'), ('Yorkshire Ambulance Service NHS Trust', 'Yorkshire Ambulance Service NHS Trust'), ('Other', 'Other')], max_length=500)),
                ('ethnicity', models.CharField(blank=True, choices=[('Asian or Asian British', [('IN', 'Indian'), ('PK', 'Pakistani'), ('BD', 'Bangladeshi'), ('CH', 'Chinese'), ('OA', 'Any other Asian background')]), ('Black, Black British, Caribbean or African', [('CB', 'Caribbean'), ('AF', 'African'), ('OB', 'Any other Black, Black British, or Caribbean background')]), ('Mixed or multiple ethnic groups', [('WC', 'White and Black Caribbean'), ('WA', 'White and Black African'), ('WS', 'White and Asian'), ('OM', 'Any other Mixed or multiple ethnic background')]), ('White', [('BR', 'English, Welsh, Scottish, Northern Irish or British'), ('IR', 'Irish'), ('GT', 'Gypsy or Irish Traveller'), ('RO', 'Roma'), ('OW', 'Any other White background')]), ('Other ethnic group', [('AR', 'Arab'), ('OG', 'Any other ethnic group')])], max_length=50)),
                ('language', models.CharField(blank=True, choices=[('ab', 'Abkhazian'), ('aa', 'Afar'), ('af', 'Afrikaans'), ('ak', 'Akan'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic'), ('an', 'Aragonese'), ('hy', 'Armenian'), ('as', 'Assamese'), ('av', 'Avaric'), ('ae', 'Avestan'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('bm', 'Bambara'), ('ba', 'Bashkir'), ('eu', 'Basque'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('bi', 'Bislama'), ('bs', 'Bosnian'), ('br', 'Breton'), ('bg', 'Bulgarian'), ('my', 'Burmese'), ('ca', 'Catalan'), ('ch', 'Chamorro'), ('ce', 'Chechen'), ('zh', 'Chinese'), ('cu', 'Church Slavic'), ('cv', 'Chuvash'), ('kw', 'Cornish'), ('co', 'Corsican'), ('cr', 'Cree'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('dv', 'Dhivehi'), ('nl', 'Dutch'), ('dz', 'Dzongkha'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('ee', 'Ewe'), ('fo', 'Faroese'), ('fj', 'Fijian'), ('fi', 'Finnish'), ('fr', 'French'), ('ff', 'Fulah'), ('gl', 'Galician'), ('lg', 'Ganda'), ('ka', 'Georgian'), ('de', 'German'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('ht', 'Haitian'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('hz', 'Herero'), ('hi', 'Hindi'), ('ho', 'Hiri Motu'), ('hu', 'Hungarian'), ('is', 'Icelandic'), ('io', 'Ido'), ('ig', 'Igbo'), ('id', 'Indonesian'), ('ia', 'Interlingua (International Auxiliary Language Association)'), ('ie', 'Interlingue'), ('iu', 'Inuktitut'), ('ik', 'Inupiaq'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('jv', 'Javanese'), ('kl', 'Kalaallisut'), ('kn', 'Kannada'), ('kr', 'Kanuri'), ('ks', 'Kashmiri'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('ki', 'Kikuyu'), ('rw', 'Kinyarwanda'), ('ky', 'Kirghiz'), ('kv', 'Komi'), ('kg', 'Kongo'), ('ko', 'Korean'), ('kj', 'Kuanyama'), ('ku', 'Kurdish'), ('lo', 'Lao'), ('la', 'Latin'), ('lv', 'Latvian'), ('li', 'Limburgan'), ('ln', 'Lingala'), ('lt', 'Lithuanian'), ('lu', 'Luba-Katanga'), ('lb', 'Luxembourgish'), ('mk', 'Macedonian'), ('mg', 'Malagasy'), ('ms', 'Malay (macrolanguage)'), ('ml', 'Malayalam'), ('mt', 'Maltese'), ('gv', 'Manx'), ('mi', 'Maori'), ('mr', 'Marathi'), ('mh', 'Marshallese'), ('el', 'Modern Greek (1453-)'), ('mn', 'Mongolian'), ('na', 'Nauru'), ('nv', 'Navajo'), ('ng', 'Ndonga'), ('ne', 'Nepali (macrolanguage)'), ('nd', 'North Ndebele'), ('se', 'Northern Sami'), ('no', 'Norwegian'), ('nb', 'Norwegian Bokmål'), ('nn', 'Norwegian Nynorsk'), ('ny', 'Nyanja'), ('oc', 'Occitan (post 1500)'), ('oj', 'Ojibwa'), ('or', 'Oriya (macrolanguage)'), ('om', 'Oromo'), ('os', 'Ossetian'), ('pi', 'Pali'), ('pa', 'Panjabi'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ps', 'Pushto'), ('qu', 'Quechua'), ('ro', 'Romanian'), ('rm', 'Romansh'), ('rn', 'Rundi'), ('ru', 'Russian'), ('sm', 'Samoan'), ('sg', 'Sango'), ('sa', 'Sanskrit'), ('sc', 'Sardinian'), ('gd', 'Scottish Gaelic'), ('sr', 'Serbian'), ('sh', 'Serbo-Croatian'), ('sn', 'Shona'), ('ii', 'Sichuan Yi'), ('sd', 'Sindhi'), ('si', 'Sinhala'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('so', 'Somali'), ('nr', 'South Ndebele'), ('st', 'Southern Sotho'), ('es', 'Spanish'), ('su', 'Sundanese'), ('sw', 'Swahili (macrolanguage)'), ('ss', 'Swati'), ('sv', 'Swedish'), ('tl', 'Tagalog'), ('ty', 'Tahitian'), ('tg', 'Tajik'), ('ta', 'Tamil'), ('tt', 'Tatar'), ('te', 'Telugu'), ('th', 'Thai'), ('bo', 'Tibetan'), ('ti', 'Tigrinya'), ('to', 'Tonga (Tonga Islands)'), ('ts', 'Tsonga'), ('tn', 'Tswana'), ('tr', 'Turkish'), ('tk', 'Turkmen'), ('tw', 'Twi'), ('ug', 'Uighur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('ve', 'Venda'), ('vi', 'Vietnamese'), ('vo', 'Volapük'), ('wa', 'Walloon'), ('cy', 'Welsh'), ('fy', 'Western Frisian'), ('wo', 'Wolof'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('yo', 'Yoruba'), ('za', 'Zhuang'), ('zu', 'Zulu')], max_length=50)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('first_login', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupConversation',
            fields=[
                ('conversation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peer_support.conversation')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            bases=('peer_support.conversation',),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('age_of_diagnosis', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('referral_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
            },
            bases=('peer_support.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('child_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('child_age_of_diagnosis', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
            bases=('peer_support.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('age_of_diagnosis', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
            bases=('peer_support.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('DF', 'Default theme'), ('LM', 'Light mode'), ('DM', 'Dark mode')], default='DF', max_length=50)),
                ('font', models.CharField(choices=[('DF', 'Default font'), ('AR', 'Arial'), ('CA', 'Calibri')], default='DF', max_length=50)),
                ('font_size', models.CharField(choices=[('DF', 'Default size'), ('LG', 'Large'), ('XL', 'Extra large')], default='DF', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peer_support.response')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='peer_support.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('other', 'Other')], max_length=50)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('friend_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peer_support.friendrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reported', models.BooleanField(default=False)),
                ('previous_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peer_support.message')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_by', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visible_to', models.ManyToManyField(blank=True, related_name='visible_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(blank=True, to='peer_support.message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='conversations',
            field=models.ManyToManyField(blank=True, to='peer_support.conversation'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='peer_support.mentor')),
            ],
        ),
    ]
