# Generated by Django 4.2.6 on 2024-02-14 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unread_messages',
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
