# Generated by Django 4.2.10 on 2024-03-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='transplant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='transplant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='transplant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
