# Generated by Django 4.2.10 on 2024-03-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(blank=True, default='profile_pictures/sky.jpg', max_length=500),
        ),
    ]
