# Generated by Django 4.2.10 on 2024-03-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_reported',
        ),
    ]
