# Generated by Django 4.2.10 on 2024-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('other', 'Other')], default='spam', max_length=50),
        ),
    ]
