# Generated by Django 4.2.6 on 2024-01-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
        migrations.CreateModel(
            name='GroupConversation',
            fields=[
                ('conversation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peer_support.conversation')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            bases=('peer_support.conversation',),
        ),
    ]
