# Generated by Django 4.2.6 on 2024-02-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='previous_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peer_support.message'),
        ),
    ]
