# Generated by Django 4.2.10 on 2024-03-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(blank='static/profile_pictures/Firefly Create social media avatar 15605.jpg', max_length=500),
        ),
    ]
