# Generated by Django 4.2.6 on 2024-02-11 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('DF', 'Default theme'), ('LM', 'Light mode'), ('DM', 'Dark mode')], default='DF', max_length=50)),
                ('font', models.CharField(choices=[('DF', 'Default font'), ('AR', 'Arial'), ('CA', 'Calibri')], default='DF', max_length=50)),
                ('font_size', models.CharField(choices=[('DF', 'Default size'), ('LG', 'Large'), ('XL', 'Extra large')], default='DF', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
