# Generated by Django 4.2.6 on 2024-01-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0002_parent_patient_user_bio_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='disease',
            new_name='condition',
        ),
    ]
