# Generated by Django 4.2.10 on 2024-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0002_alter_postcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='G', max_length=10),
        ),
    ]
