# Generated by Django 4.2.10 on 2024-03-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0002_mentor_transplant_parent_transplant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='transplant',
            new_name='child_transplant',
        ),
    ]
