# Generated by Django 4.2.10 on 2024-03-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0003_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='reporter',
        ),
    ]
