# Generated by Django 4.2.10 on 2024-03-13 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0003_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
