# Generated by Django 5.0.2 on 2024-02-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0003_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
