# Generated by Django 4.2.6 on 2024-01-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0003_rename_disease_patient_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='child_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
