# Generated by Django 4.2.6 on 2024-01-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0003_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
