# Generated by Django 5.0.2 on 2024-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0004_mentor_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='claimed',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='referral_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
