# Generated by Django 4.2.6 on 2024-01-31 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0004_alter_parent_child_condition_alter_patient_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
