# Generated by Django 4.2.6 on 2024-02-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0005_alter_parent_options_alter_patient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
