# Generated by Django 4.2.6 on 2024-02-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0006_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
