# Generated by Django 4.2.6 on 2024-02-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0007_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age_of_diagnosis',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
