# Generated by Django 4.2.6 on 2024-02-01 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0008_alter_patient_age_of_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='child_age_of_diagnosis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age_of_diagnosis',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
