# Generated by Django 4.2.6 on 2024-02-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0010_alter_user_language_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(blank=True, to='peer_support.message'),
        ),
        migrations.AlterField(
            model_name='user',
            name='conversations',
            field=models.ManyToManyField(blank=True, to='peer_support.conversation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unread_messages',
            field=models.ManyToManyField(blank=True, to='peer_support.message'),
        ),
    ]
