# Generated by Django 4.2.6 on 2024-02-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_support', '0015_remove_groupconversation_conversation_ptr_and_more'),
    ]

    operations = [
    ]
