CONDITION_CHOICES = [
    ("", "---------"),
    ("Acute fatty liver disease of pregnancy", "Acute fatty liver disease of pregnancy"),
    ("Alcohol-related liver disease (ARLD)", "Alcohol-related liver disease (ARLD)"),
    ("Alpha 1 antitrypsin deficiency (AATD)", "Alpha 1 antitrypsin deficiency (AATD)"),
    ("Autoimmune hepatitis (AIH)", "Autoimmune hepatitis (AIH)"),
    ("Benign liver tumours", "Benign liver tumours"),
    ("Bile duct cancer", "Bile duct cancer"),
    ("Bile duct cysts", "Bile duct cysts"),
    ("Biliary cystadenoma", "Biliary cystadenoma"),
    ("Biliary cysts (also called choledochal cysts)", "Biliary cysts (also called choledochal cysts)"),
    ("Biliary hamartoma", "Biliary hamartoma"),
    ("Budd-Chiari", "Budd-Chiari"),
    ("Cancer", "Cancer"),
    ("Caroli disease and Caroli syndrome", "Caroli disease and Caroli syndrome"),
    ("Cholangiocarcinoma", "Cholangiocarcinoma"),
    ("Choledochal cysts", "Choledochal cysts"),
    ("Cirrhosis", "Cirrhosis"),
    ("Congenital hepatic fibrosis", "Congenital hepatic fibrosis"),
    ("Cryptogenic liver disease", "Cryptogenic liver disease"),
    ("Cystic fibrosis related liver disease", "Cystic fibrosis related liver disease"),
    ("Cysts", "Cysts"),
    ("Drug-induced liver injury (DILI)", "Drug-induced liver injury (DILI)"),
    ("Echinococcosis (also called hydatid cysts)", "Echinococcosis (also called hydatid cysts)"),
    ("Fatty liver disease", "Fatty liver disease"),
    ("Fibrocystic liver conditions", "Fibrocystic liver conditions"),
    ("Fibrolamellar cancer", "Fibrolamellar cancer"),
    ("Focal nodule hyperplasia", "Focal nodule hyperplasia"),
    ("Gallstones", "Gallstones"),
    ("Gilbert’s syndrome", "Gilbert’s syndrome"),
    ("Haemangioma", "Haemangioma"),
    ("Haemochromatosis", "Haemochromatosis"),
    ("Hepatic encephalopathy", "Hepatic encephalopathy"),
    ("Hepatitis A", "Hepatitis A"),
    ("Hepatitis B", "Hepatitis B"),
    ("Hepatitis C", "Hepatitis C"),
    ("Hepatitis E", "Hepatitis E"),
    ("Hepatic cysts", "Hepatic cysts"),
    ("Hepatocellular adenoma", "Hepatocellular adenoma"),
    ("Hepatocellular carcinoma (HCC)", "Hepatocellular carcinoma (HCC)"),
    ("Hepatoma", "Hepatoma"),
    ("Hydatid cysts (might be called hydatidosis or hydatid disease)", "Hydatid cysts (might be called hydatidosis or hydatid disease)"),
    ("Intrahepatic cholestasis of pregnancy (ICP)", "Intrahepatic cholestasis of pregnancy (ICP)"),
    ("Liver abscesses", "Liver abscesses"),
    ("Liver cancer", "Liver cancer"),
    ("Liver cysts", "Liver cysts"),
    ("Liver haemangioma", "Liver haemangioma"),
    ("Metabolic dysfunction-associated steatotic liver disease (MASLD)", "Metabolic dysfunction-associated steatotic liver disease (MASLD)"),
    ("Non-alcohol related fatty liver disease (NAFLD)", "Non-alcohol related fatty liver disease (NAFLD)"),
    ("Porphyria", "Porphyria"),
    ("Portal hypertension", "Portal hypertension"),
    ("Polycystic liver disease", "Polycystic liver disease"),
    ("Primary sclerosing cholangitis (PSC)", "Primary sclerosing cholangitis (PSC)"),
    ("Primary biliary cholangitis (PBC)", "Primary biliary cholangitis (PBC)"),
    ("Simple liver cysts", "Simple liver cysts"),
    ("Viral hepatitis", "Viral hepatitis"),
    ("Wilson’s disease", "Wilson’s disease"),
    ("Other", "Other"),
]

USER_TYPE_CHOICES = [
    ('', '---------'),
    ('PT', 'Patient'),
    ('PR', 'Parent'),
    ('MT', 'Mentor'),
    ('PF', 'Professional'),
]

SORT_USER_CHOICES = [
    ('', 'Best Match'), 
    ('username_asc', 'Username Ascending'),
    ('username_desc', 'Username Descending'),
    ('age_asc', 'Age Ascending'),
    ('age_desc', 'Age Descending'),
]

TRANSPLANT_CHOICES = [
    ('', '---------'),
    ('Y', 'Yes'), 
    ('N', 'No'),
]

POST_VISIBILITY_CHOICES = [
    ("G", "Global"),
    ("F", "Friends"),
]